import dotenv from "dotenv";

dotenv.config();
const BASE_URL = process.env.BASE_URL;
export const products = [
  {
    category: "Clothes",
    sub_category: "Men's Wear",
    title: "Jeans",
    description: "this is jeans",
    price: 200,
    rating: {
      rate: 4.5,
      count: 200,
    },
    image: "http://localhost:5173/Pictures/jeans.webp",
  },
  {
    category: "Clothes",
    sub_category: "Men's Wear",
    title: "T-shirt",
    description: "this is a T-shirt",
    price: 150,
    rating: {
      rate: 4.2,
      count: 150,
    },
    image: "http://localhost:5173/Pictures/t-shirt.jpeg",
  },
  {
    category: "Clothes",
    sub_category: "Women's Wear",
    title: "Dress",
    description: "this is a stylish dress",
    price: 3000,
    rating: {
      rate: 4.7,
      count: 20,
    },
    image: "http://localhost:5173/Pictures/Dress.webp",
  },
  {
    category: "Clothes",
    sub_category: "Women's Wear",
    title: "Blouse",
    description: "this is a casual blouse",
    price: 120,
    rating: {
      rate: 4.0,
      count: 180,
    },
    image: "http://localhost:5173\Pictures\blouse.jpg",
  },
  {
    category: "Clothes",
    sub_category: "Men's Wear",
    title: "Jacket",
    description: "this is a winter jacket",
    price: 450,
    rating: {
      rate: 4.6,
      count: 100,
    },
    image:"http://localhost:5173/Pictures/jacket.jpg",
  },
  {
    category: "Electronics",
    sub_category: "Mobile Phones",
    title: "Smartphone",
    description: "latest model smartphone with great features",
    price: 100000,
    rating: {
      rate: 4.8,
      count: 500,
    },
    image:"http://localhost:5173/Pictures/iphone.jpg",
  },
  {
    category: "Electronics",
    sub_category: "Mobile Phones",
    title: "Smartphone Case",
    description: "durable smartphone case",
    price: 150,
    rating: {
      rate: 4.3,
      count: 300,
    },
    image:"http://localhost:5173/Pictures/iphone_case.jpg",
  },
  {
    category: "Electronics",
    sub_category: "Laptops",
    title: "Laptop",
    description: "high performance laptop for gaming and work",
    price: 200000,
    rating: {
      rate: 4.9,
      count: 150,
    },
    image:"http://localhost:5173/Pictures/laptop.jpg",
  },
  {
    category: "Electronics",
    sub_category: "Laptops",
    title: "Laptop Sleeve",
    description: "protective sleeve for laptops",
    price: 130,
    rating: {
      rate: 4.1,
      count: 80,
    },
    image:"http://localhost:5173/Pictures/laptop_sleeve.jpg",
  },
  {
    category: "Electronics",
    sub_category: "Headphones",
    title: "Wireless Headphones",
    description: "noise-cancelling wireless headphones",
    price: 200,
    rating: {
      rate: 4.7,
      count: 400,
    },
    image: "http://localhost:5173/Pictures/Headphones.jpg",
  },
  {
    category: "Accessories",
    sub_category: "Watches",
    title: "Smart Watch",
    description: "track your health and fitness with a smart watch",
    price: 500,
    rating: {
      rate: 4.4,
      count: 220,
    },
    image:"http://localhost:5173/Pictures/SmartWatch.webp",
  },
  {
    category: "Accessories",
    sub_category: "Jewelry",
    title: "Necklace",
    description: "beautiful gold necklace",
    price: 300,
    rating: {
      rate: 4.9,
      count: 130,
    },
    image: "http://localhost:5173/Pictures/Necklace.jpeg",
  },
  {
    category: "Accessories",
    sub_category: "Bags",
    title: "Leather Handbag",
    description: "premium leather handbag",
    price: 250,
    rating: {
      rate: 4.6,
      count: 90,
    },
    image: "http://localhost:5173/Pictures/Handbag.jpg",
  },
  {
    category: "Accessories",
    sub_category: "Sunglasses",
    title: "Sunglasses",
    description: "stylish sunglasses for summer",
    price: 100,
    rating: {
      rate: 4.3,
      count: 350,
    },
    image: "http://localhost:5173/Pictures/Sunglass.webp",
  },
  {
    category: "Groceries",
    sub_category: "Fruits",
    title: "Apple",
    description: "fresh and organic apples",
    price: 15,
    rating: {
      rate: 4.8,
      count: 200,
    },
    image:"http://localhost:5173/Pictures/Apple.jpg",
  },
  {
    category: "Groceries",
    sub_category: "Vegetables",
    title: "Carrot",
    description: "fresh carrots from local farm",
    price: 2,
    rating: {
      rate: 4.6,
      count: 180,
    },
    image:"http://localhost:5173/Pictures/Carrot.webp",
  },
  {
    category: "Groceries",
    sub_category: "Beverages",
    title: "Orange Juice",
    description: "freshly squeezed orange juice",
    price: 4,
    rating: {
      rate: 4.7,
      count: 300,
    },
    image:"http://localhost:5173/Pictures/Orange_juice.jpg",
  },
  {
    category: "Groceries",
    sub_category: "Snacks",
    title: "Chips",
    description: "crispy potato chips",
    price: 5,
    rating: {
      rate: 4.2,
      count: 400,
    },
    image:"http://localhost:5173/Pictures/Lays.png",
  },
  {
    category: "Groceries",
    sub_category: "Beverages",
    title: "Coffee",
    description: "premium ground coffee",
    price: 10,
    rating: {
      rate: 4.5,
      count: 350,
    },
    image: "http://localhost:5173/Pictures/coffee.webp",
  },
  {
    category: "Groceries",
    sub_category: "Fruits",
    title: "Banana",
    description: "fresh bananas",
    price: 4,
    rating: {
      rate: 4.4,
      count: 500,
    },
    image:"http://localhost:5173/Pictures/Carrot.webp",
  },
];